=== habanero-rice/cnc-ocr/examples/tuned-cholesky/hpt/hpt.dtd
<!-- ******************************************************************** -->
<!-- Hierarchical place Tree (HPT) DTD                                    -->
<!-- Version 0.1                                                          -->
<!-- ******************************************************************** -->

<!ELEMENT HPT (place+)>
<!ATTLIST HPT 
          version (0.1|99.99) "0.1"
          info CDATA #IMPLIED>
<!ATTLIST place
          num CDATA #IMPLIED
          did CDATA #IMPLIED
          type (mem | cache | comm | nvgpu | amgpu | fpga | pgas) "cache"
          size CDATA #IMPLIED
          unitSize CDATA #IMPLIED>

<!ELEMENT place (place*, worker*)>
<!ELEMENT worker EMPTY>

<!ATTLIST worker
          num CDATA #IMPLIED
          did CDATA #IMPLIED
          type (cpu|gpu|comm) "cpu">

=== habanero-rice/cnc-ocr/examples/tuned-cholesky/hpt/hpt-davinci-comm.xml
<?xml version="1.0"?>
<!DOCTYPE HPT SYSTEM "hpt.dtd">

<HPT version="0.1" info="an HPT (for comm worker enabled) for DaVinci, 2 hex core2 Intel Westmere processors">
    <place num="1" type="mem">
        <place num="1" type="cache"> <!-- socket with common L3 in each -->
            <place num="5" type="cache"> <!-- 6 L2/L1 cache per socket -->
                <worker num="1"/> 
            </place>
        </place>
        <place num="1" type="cache"> <!-- socket with common L3 in each -->
            <place num="6" type="cache"> <!-- 6 L2/L1 cache per socket -->
                <worker num="1"/> 
            </place>
        </place>
        <worker num="1" type="comm"/> <!-- comm worker -->
    </place>
</HPT>

=== habanero-rice/cnc-ocr/examples/hpt/hpt-foobar-comm.xml
<?xml version="1.0"?>
<!DOCTYPE HPT SYSTEM "hpt.dtd">

<HPT version="0.1" info="an HPT (for comm worker enabled) for Foobar, 2 sockets, 8 cores per socket, 2-way hyperthreaded = 32 hw threads">
    <place num="1" type="mem">
        <place num="1" type="cache"> <!-- socket with common L3 in each -->
            <place num="7" type="cache"> <!-- 7 L2/L1 cache per socket -->
                <worker num="1"/> 
            </place>
        </place>
        <place num="1" type="cache"> <!-- socket with common L3 in each -->
            <place num="8" type="cache"> <!-- 8 L2/L1 cache per socket -->
                <worker num="1"/> 
            </place>
        </place>
        <worker num="1" type="comm"/> <!-- comm worker -->
    </place>
</HPT>
